
# The name of your website.
name: Felipe Orlando

description:

  # Description of my site. This will show up in google.
  meta: Olá! Meu nome é Felipe Orlando, desenvolvedor web, e este é meu blog. Now, say my name!

  # Description of your site. This will show up on the front page.
  subtitle: "Olá! Meu nome é Felipe Orlando, desenvolvedor web, e este é meu blog. Se sua busca é por conhecimento, veio ao lugar certo. Acho. :)"
  # subtitle: Holo Alfa is a minimalist, mobile first Jekyll theme with focus on readability and content. <a href="https://github.com/steinvc/holo-alfa">&lt;/&gt; on Github</a>.

author:
  name: Felipe Orlando

  # Necessary for contact page
  email: bee.sql@gmail.com

  # Optional text (html) to display after author name. Leave empty if you don't
  # want it.
  info: "Desenvolvedor Ruby (fws. Rails, Sinatra), PHP (fws. Laravel, Zend) e Javascript (Node.js, Angular.js e jQuery). Back-ender por diversão, front-end por obrigação e designer por natureza."

# url: http://steinvc.github.io
# baseurl: "/"

# language attribute in <html> element.
lang: pt-BR

# FROM THIS POINT ON EVERYTHING IS OPTIONAL

##############
# APPEREANCE #
##############

# If you want to show the subtitle anywhere else than the front page, use
# {% include subtitle.html %} to include it anywhere you want.
show-subtitle: true
display-social-icons: true

footer-text: Aprenda e compartilhe conhecimento sem moderação.<br>Tema <a href="http://steinvc.github.io/holo-alfa/">Holo Alfa</a> desenvolvido por <a href="http://steinvc.github.io/holo-alfa/">Stijn</a>.

# Preferably 64px in height. Leave empty = disable.
logo-image: # /img/logo.png

# Toolbar color for Chrome on Android.
theme-color-attr: "#66FF33"

# Color of Microsoft live Tile.
ms-tile-color: "#66FF33"

# Color used throughout the theme. Format: R, G, B.
theme-color: 102, 255, 51 # Original: 0, 240, 255

# Text color used throughout the theme. Format: R, G, B.
text-color: 0, 0, 0 # Original: 0, 0, 0

# Background color used throughout the theme. Format: R, G, B.
# Note: if you change the background color AND you use cover images, you should
#       also change the CSS gradient in "_includes\gradient.css" to match the
#       background color. Edit and copy it from here:
#       http://www.colorzilla.com/gradient-editor/#ffffff+0,ffffff+100&0+0,1+100
background-color: 255, 255, 255 # Original: 255, 255, 255

display-author-post-page: true
display-author-front-page: true

# http://alanwsmith.com/jekyll-liquid-date-formatting-examples
date_format: "%d/%m/%Y"

# Minimal screen-width after which the navigation will change position from
# vertical to horizontal.
nav-breaking-point: 520px

# Number of posts on each page.
paginate: 3

# Display links for the previous and next post on post pages.
display-next-prev-post: false

# Leave empty if you don't want comments on post pages.
disqus-shortname: fbeegle


################
# SOCIAL ICONS #
################

# Use a complete url here, including http:// and such. Requiring just usernames
# has been considered, but this is way more customizable.
twitter:
youtube:
instagram: http://instagram.com/fbeegle
tumblr:
facebook: http://fb.com/fbeegle
google-plus:
reddit:
soundcloud:
medium:
linkedin: http://lnkdin.me/felipe
github: http://github.com/fbeegle
behance:
codepen:
dribbble:
trello:
stack-overflow:
bitcoin:
paypal:


#####################
# CUSTOMIZABLE TEXT #
#####################

# Useful for translating into other languages.

var_on_the_web: On the web
var_read: Ler # Text after each post summary on the homepage.
var_newer: Novos
var_older: Antigos
var_next_post: Próxima postagem
var_previous_post: Postagem anterior
var_less_than_a_minute_read: Menos de um minuto de leitura
var_min_read: min de leitura # Text after reading time. Example: 5 min read.
var_post_by: Postado por
var_guest_post_by: Postado por
var_your_email: Seu email
var_your_message: Sua mensagem
var_send_message: Enviar


##################
# BUILD SETTINGS #
##################

# You don't have to change these.

exclude: [vendor]
highlighter: pygments
kramdown:
  input: GFM
paginate_path: "/page-:num/"
permalink: pretty
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: "<!--more-->"
